package ai.ecma.lib.enums;

public enum BotStateEnum {
    CHOOSE_LANG,
    CHOOSE_REGION,
    CHOOSE_DISTRICT,
    SEND_PHONE_NUMBER,
    VERIFY_CODE,
    PRIVACY_POLICY,
    MENU,
    SELECT_CATEGORY,
    SELECT_SUBCATEGORY,
    SELECT_PRODUCT,
    SELECT_PRODUCT_QUANTITY,
    BASKET,
    GEOLOCATION,
    SELECT_PAY_TYPE,
    PAY_WITH_INVOICE,
}
